//=========================================================
// src/InitDevice.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

// USER INCLUDES
#include <SI_EFM8BB50_Register_Enums.h>
#include "InitDevice.h"

// USER PROTOTYPES
// USER FUNCTIONS

// $[Library Includes]
// [Library Includes]$

//==============================================================================
// enter_DefaultMode_from_RESET
//==============================================================================
extern void
enter_DefaultMode_from_RESET (void)
{
  // $[Config Calls]
  // Save the SFRPAGE
  uint8_t SFRPAGE_save = SFRPAGE;
  WDT_0_enter_DefaultMode_from_RESET ();
  PORTS_0_enter_DefaultMode_from_RESET ();
  PBCFG_0_enter_DefaultMode_from_RESET ();
  CLOCK_0_enter_DefaultMode_from_RESET ();
  CIP51_0_enter_DefaultMode_from_RESET ();
  ADC12_0_enter_DefaultMode_from_RESET ();
  TIMER16_2_enter_DefaultMode_from_RESET ();
  PCA_0_enter_DefaultMode_from_RESET ();
  PCACH_0_enter_DefaultMode_from_RESET ();
  INTERRUPT_0_enter_DefaultMode_from_RESET ();
  // Restore the SFRPAGE
  SFRPAGE = SFRPAGE_save;
  // [Config Calls]$

}

extern void
WDT_0_enter_DefaultMode_from_RESET (void)
{
  // $[Watchdog Timer Init Variable Declarations]
  uint32_t i;
  bool ea;
  // [Watchdog Timer Init Variable Declarations]$

  // $[WDTCN - Watchdog Timer Control]
  SFRPAGE = 0x00;

  // Feed WDT timer before disabling (Erratum WDT_E102)
  WDTCN = 0xA5;

  // Add 2 LFO cycle delay before disabling WDT (Erratum WDT_E102)
  for (i = 0; i < (2 * 3062500UL) / (80000 * 3); i++)
    {
      NOP ();
    }

  // Disable WDT
  ea = IE_EA;
  IE_EA = 0;
  WDTCN = 0xDE;
  WDTCN = 0xAD;
  IE_EA = ea;

  // [WDTCN - Watchdog Timer Control]$

}

extern void
PORTS_0_enter_DefaultMode_from_RESET (void)
{
  // $[P0 - Port 0 Pin Latch]
  /***********************************************************************
   - P0.0 is high. Set P0.0 to drive or float high
   - P0.1 is low. Set P0.1 to drive low
   - P0.2 is high. Set P0.2 to drive or float high
   - P0.3 is high. Set P0.3 to drive or float high
   - P0.4 is low. Set P0.4 to drive low
   - P0.5 is low. Set P0.5 to drive low
   - P0.6 is high. Set P0.6 to drive or float high
   - P0.7 is low. Set P0.7 to drive low
   ***********************************************************************/
  P0 = P0_B0__HIGH | P0_B1__LOW | P0_B2__HIGH | P0_B3__HIGH | P0_B4__LOW
      | P0_B5__LOW | P0_B6__HIGH | P0_B7__LOW;
  // [P0 - Port 0 Pin Latch]$

  // $[P0MDOUT - Port 0 Output Mode]
  /***********************************************************************
   - P0.0 output is open-drain
   - P0.1 output is push-pull
   - P0.2 output is open-drain
   - P0.3 output is open-drain
   - P0.4 output is push-pull
   - P0.5 output is push-pull
   - P0.6 output is open-drain
   - P0.7 output is push-pull
   ***********************************************************************/
  P0MDOUT = P0MDOUT_B0__OPEN_DRAIN | P0MDOUT_B1__PUSH_PULL
      | P0MDOUT_B2__OPEN_DRAIN | P0MDOUT_B3__OPEN_DRAIN | P0MDOUT_B4__PUSH_PULL
      | P0MDOUT_B5__PUSH_PULL | P0MDOUT_B6__OPEN_DRAIN | P0MDOUT_B7__PUSH_PULL;
  // [P0MDOUT - Port 0 Output Mode]$

  // $[P0MDIN - Port 0 Input Mode]
  /***********************************************************************
   - P0.0 pin is configured for digital mode
   - P0.1 pin is configured for digital mode
   - P0.2 pin is configured for analog mode
   - P0.3 pin is configured for digital mode
   - P0.4 pin is configured for digital mode
   - P0.5 pin is configured for digital mode
   - P0.6 pin is configured for digital mode
   - P0.7 pin is configured for digital mode
   ***********************************************************************/
  P0MDIN = P0MDIN_B0__DIGITAL | P0MDIN_B1__DIGITAL | P0MDIN_B2__ANALOG
      | P0MDIN_B3__DIGITAL | P0MDIN_B4__DIGITAL | P0MDIN_B5__DIGITAL
      | P0MDIN_B6__DIGITAL | P0MDIN_B7__DIGITAL;
  // [P0MDIN - Port 0 Input Mode]$

  // $[P0SKIP - Port 0 Skip]
  /***********************************************************************
   - P0.0 pin is skipped by the crossbar
   - P0.1 pin is not skipped by the crossbar
   - P0.2 pin is skipped by the crossbar
   - P0.3 pin is skipped by the crossbar
   - P0.4 pin is not skipped by the crossbar
   - P0.5 pin is not skipped by the crossbar
   - P0.6 pin is skipped by the crossbar
   - P0.7 pin is not skipped by the crossbar
   ***********************************************************************/
  P0SKIP = P0SKIP_B0__SKIPPED | P0SKIP_B1__NOT_SKIPPED | P0SKIP_B2__SKIPPED
      | P0SKIP_B3__SKIPPED | P0SKIP_B4__NOT_SKIPPED | P0SKIP_B5__NOT_SKIPPED
      | P0SKIP_B6__SKIPPED | P0SKIP_B7__NOT_SKIPPED;
  // [P0SKIP - Port 0 Skip]$

  // $[P0MASK - Port 0 Mask]
  // [P0MASK - Port 0 Mask]$

  // $[P0MAT - Port 0 Match]
  // [P0MAT - Port 0 Match]$

}

extern void
PBCFG_0_enter_DefaultMode_from_RESET (void)
{
  // $[XBR2 - Port I/O Crossbar 2]
  /***********************************************************************
   - Weak Pullups enabled 
   - Crossbar enabled
   - PWM single ended output for all enabled channels
   - PWM0 Ch0, Ch1, and Ch2 routed to Port pin
   ***********************************************************************/
  XBR2 = XBR2_WEAKPUD__PULL_UPS_ENABLED | XBR2_XBARE__ENABLED
      | XBR2_PWMDE__SINGLE | XBR2_PWME__PWM0CH012;
  // [XBR2 - Port I/O Crossbar 2]$

  // $[PRTDRV - Port Drive Strength]
  /***********************************************************************
   - Coexistence enabled
   - All pins on P0 use high drive strength
   - All pins on P1 use high drive strength
   - All pins on P2 use high drive strength
   ***********************************************************************/
  PRTDRV = PRTDRV_COEX__ENABLED | PRTDRV_P0DRV__HIGH_DRIVE
      | PRTDRV_P1DRV__HIGH_DRIVE | PRTDRV_P2DRV__HIGH_DRIVE;
  // [PRTDRV - Port Drive Strength]$

  // $[XBR0 - Port I/O Crossbar 0]
  // [XBR0 - Port I/O Crossbar 0]$

  // $[XBR1 - Port I/O Crossbar 1]
  /***********************************************************************
   - CEX0 routed to Port pin
   - ECI unavailable at Port pin
   - T0 unavailable at Port pin
   - T1 unavailable at Port pin
   - T2 unavailable at Port pin
   ***********************************************************************/
  XBR1 = XBR1_PCA0ME__CEX0 | XBR1_ECIE__DISABLED | XBR1_T0E__DISABLED
      | XBR1_T1E__DISABLED | XBR1_T2E__DISABLED;
  // [XBR1 - Port I/O Crossbar 1]$

}

extern void
CLOCK_0_enter_DefaultMode_from_RESET (void)
{
  // $[HFOSC0 49 and 49/1.5 MHz Oscillator Setup]
  // Ensure SYSCLK is > 24 MHz before switching to 49 MHz or 49/1.5 MHz Oscillator
  CLKSEL = CLKSEL_CLKSL__HFOSC0_clk24p5 | CLKSEL_CLKDIV__SYSCLK_DIV_1;
  while ((CLKSEL & CLKSEL_DIVRDY__BMASK) == CLKSEL_DIVRDY__NOT_READY)
    ;
  // [HFOSC0 49 and 49/1.5 MHz Oscillator Setup]$

  // $[CLKSEL - Clock Select]
  /***********************************************************************
   - Clock derived from the Internal High Frequency Oscillator 49 MHz
   - SYSCLK is equal to selected clock source divided by 1
   ***********************************************************************/
  CLKSEL = CLKSEL_CLKSL__HFOSC0_clk49 | CLKSEL_CLKDIV__SYSCLK_DIV_1;
  while ((CLKSEL & CLKSEL_DIVRDY__BMASK) == CLKSEL_DIVRDY__NOT_READY)
    ;
  // [CLKSEL - Clock Select]$

  // $[CLKGRP0 - Clock Group 0]
  /***********************************************************************
   - Select SYSCLK divided by CLKSEL.CLKDIV 
   - Divide selected clock group by 2
   - Disable charge pump refresh clock
   - Enable SAR clock
   ***********************************************************************/
  CLKGRP0 = CLKGRP0_CLKGRP0SL__SYSCLK | CLKGRP0_CLKDIVSL__DIV2
      | CLKGRP0_EN_CPCLK__DISABLE | CLKGRP0_EN_SARCLK__ENABLE;
  // [CLKGRP0 - Clock Group 0]$

}

extern void
CIP51_0_enter_DefaultMode_from_RESET (void)
{
  // $[PFE0CN - Prefetch Engine Control]
  /***********************************************************************
   - Enables the Prefetch Engine when SYSCLK < 50 MHz
   ***********************************************************************/
  SFRPAGE = 0x10;
  PFE0CN = PFE0CN_FLRT__SYSCLK_BELOW_50_MHZ;
  // [PFE0CN - Prefetch Engine Control]$

}

extern void
INTERRUPT_0_enter_DefaultMode_from_RESET (void)
{
  // $[EIE1 - Extended Interrupt Enable 1]
  /***********************************************************************
   - Disable ADC0 Conversion Complete interrupt
   - Disable ADC0 Window Comparison interrupt
   - Disable all Port Match interrupts
   - Enable interrupt requests generated by PCA0
   - Disable all SMB0 interrupts
   - Disable Timer 3 interrupts
   ***********************************************************************/
  EIE1 = EIE1_EADC0__DISABLED | EIE1_EWADC0__DISABLED | EIE1_EMAT__DISABLED
      | EIE1_EPCA0__ENABLED | EIE1_ESMB0__DISABLED | EIE1_ET3__DISABLED;
  // [EIE1 - Extended Interrupt Enable 1]$

  // $[EIE2 - Extended Interrupt Enable 2]
  // [EIE2 - Extended Interrupt Enable 2]$

  // $[EIP1H - Extended Interrupt Priority 1 High]
  // [EIP1H - Extended Interrupt Priority 1 High]$

  // $[EIP1 - Extended Interrupt Priority 1 Low]
  // [EIP1 - Extended Interrupt Priority 1 Low]$

  // $[EIP2 - Extended Interrupt Priority 2]
  // [EIP2 - Extended Interrupt Priority 2]$

  // $[EIP2H - Extended Interrupt Priority 2 High]
  // [EIP2H - Extended Interrupt Priority 2 High]$

  // $[IE - Interrupt Enable]
  /***********************************************************************
   - Enable each interrupt according to its individual mask setting
   - Disable external interrupt 0
   - Disable external interrupt 1
   - Disable all SPI0 interrupts
   - Disable all Timer 0 interrupt
   - Disable all Timer 1 interrupt
   - Enable interrupt requests generated by the TF2L or TF2H flags
   - Disable UART0 interrupt
   ***********************************************************************/
  IE = IE_EA__ENABLED | IE_EX0__DISABLED | IE_EX1__DISABLED | IE_ESPI0__DISABLED
      | IE_ET0__DISABLED | IE_ET1__DISABLED | IE_ET2__ENABLED
      | IE_ES0__DISABLED;
  // [IE - Interrupt Enable]$

  // $[IP - Interrupt Priority]
  // [IP - Interrupt Priority]$

  // $[IPH - Interrupt Priority High]
  // [IPH - Interrupt Priority High]$

}

extern void
PCA_0_enter_DefaultMode_from_RESET (void)
{
  SFRPAGE = 0x00;
  // $[PCA Off]
  PCA0CN0_CR = PCA0CN0_CR__STOP;
  // [PCA Off]$

  // $[PCA0MD - PCA Mode]
  /***********************************************************************
   - PCA continues to function normally while the system controller is in
   Idle Mode
   - Disable the CF interrupt
   - System clock
   ***********************************************************************/
  PCA0MD = PCA0MD_CIDL__NORMAL | PCA0MD_ECF__OVF_INT_DISABLED
      | PCA0MD_CPS__SYSCLK;
  // [PCA0MD - PCA Mode]$

  // $[PCA0CENT - PCA Center Alignment Enable]
  // [PCA0CENT - PCA Center Alignment Enable]$

  // $[PCA0L - PCA Counter/Timer Low Byte]
  // [PCA0L - PCA Counter/Timer Low Byte]$

  // $[PCA0H - PCA Counter/Timer High Byte]
  // [PCA0H - PCA Counter/Timer High Byte]$

  // $[PCA0POL - PCA Output Polarity]
  /***********************************************************************
   - Invert polarity
   - Use default polarity
   - Use default polarity
   ***********************************************************************/
  PCA0POL = PCA0POL_CEX0POL__INVERT | PCA0POL_CEX1POL__DEFAULT
      | PCA0POL_CEX2POL__DEFAULT;
  // [PCA0POL - PCA Output Polarity]$

  // $[PCA0PWM - PCA PWM Configuration]
  // [PCA0PWM - PCA PWM Configuration]$

  // $[PCA On]
  // [PCA On]$

}

extern void
PCACH_0_enter_DefaultMode_from_RESET (void)
{
  // $[PCA0 Settings Save]
  // Select Capture/Compare register)
  PCA0PWM &= ~PCA0PWM_ARSEL__BMASK;
  // [PCA0 Settings Save]$

  // $[PCA0CPM0 - PCA Channel 0 Capture/Compare Mode]
  /***********************************************************************
   - Disable negative edge capture
   - Enable a Capture/Compare Flag interrupt request when CCF0 is set
   - Enable match function
   - 16-bit PWM selected
   - Disable positive edge capture
   - Enable comparator function
   - Enable PWM function
   - Disable toggle function
   ***********************************************************************/
  PCA0CPM0 = PCA0CPM0_CAPN__DISABLED | PCA0CPM0_ECCF__ENABLED
      | PCA0CPM0_MAT__ENABLED | PCA0CPM0_PWM16__16_BIT | PCA0CPM0_CAPP__DISABLED
      | PCA0CPM0_ECOM__ENABLED | PCA0CPM0_PWM__ENABLED | PCA0CPM0_TOG__DISABLED;
  // [PCA0CPM0 - PCA Channel 0 Capture/Compare Mode]$

  // $[PCA0CPL0 - PCA Channel 0 Capture Module Low Byte]
  // [PCA0CPL0 - PCA Channel 0 Capture Module Low Byte]$

  // $[PCA0CPH0 - PCA Channel 0 Capture Module High Byte]
  PCA0CPH0 = 0x00;
  // [PCA0CPH0 - PCA Channel 0 Capture Module High Byte]$

  // $[Auto-reload]
  // [Auto-reload]$

  // $[PCA0 Settings Restore]
  // [PCA0 Settings Restore]$

}

extern void
ADC12_0_enter_DefaultMode_from_RESET (void)
{
  // $[ADC0CN2 - ADC0 Control 2]
  // [ADC0CN2 - ADC0 Control 2]$

  // $[ADC0CN1 - ADC0 Control 1]
  /***********************************************************************
   - ADC0 operates in 10-bit mode
   - Right justified. No shifting applied
   - Perform and Accumulate 1 conversion
   ***********************************************************************/
  SFRPAGE = 0x00;
  ADC0CN1 = ADC0CN1_ADBITS__10_BIT | ADC0CN1_ADSJST__RIGHT_NO_SHIFT
      | ADC0CN1_ADRPT__ACC_1;
  // [ADC0CN1 - ADC0 Control 1]$

  // $[ADC0MX - ADC0 Multiplexer Selection]
  /***********************************************************************
   - Select ADC0.0
   ***********************************************************************/
  ADC0MX = ADC0MX_ADC0MX__ADC0P0;
  // [ADC0MX - ADC0 Multiplexer Selection]$

  // $[ADC0CF2 - ADC0 Power Control]
  /***********************************************************************
   - The ADC0 ground reference is internal ground
   - Selects 1.8V from internal fast reference as the ADC0 voltage
   reference
   - Power Up Delay Time = 0x0F
   ***********************************************************************/
  ADC0CF2 = ADC0CF2_GNDSL__GND_PIN | ADC0CF2_REFSL__1V8
      | (0x0F << ADC0CF2_ADPWR__SHIFT);
  // [ADC0CF2 - ADC0 Power Control]$

  // $[ADC0CF1 - ADC0 Configuration]
  /***********************************************************************
   - Disable external voltage reference for the ADC
   - Conversion Tracking Time = 0x0B
   ***********************************************************************/
  ADC0CF1 = ADC0CF1_RPCE__DISABLED | (0x0B << ADC0CF1_ADTK__SHIFT);
  // [ADC0CF1 - ADC0 Configuration]$

  // $[ADC0ASAL - ADC0 Autoscan Start Address Low Byte]
  // [ADC0ASAL - ADC0 Autoscan Start Address Low Byte]$

  // $[ADC0GTH - ADC0 Greater-Than High Byte]
  // [ADC0GTH - ADC0 Greater-Than High Byte]$

  // $[ADC0GTL - ADC0 Greater-Than Low Byte]
  // [ADC0GTL - ADC0 Greater-Than Low Byte]$

  // $[ADC0LTH - ADC0 Less-Than High Byte]
  // [ADC0LTH - ADC0 Less-Than High Byte]$

  // $[ADC0LTL - ADC0 Less-Than Low Byte]
  // [ADC0LTL - ADC0 Less-Than Low Byte]$

  // $[ADC0ASCF - ADC0 Autoscan Configuration]
  // [ADC0ASCF - ADC0 Autoscan Configuration]$

  // $[ADC0CN0 - ADC0 Control 0]
  /***********************************************************************
   - Enable ADC0 
   - The on-chip gain is 0.5
   ***********************************************************************/
  ADC0CN0 &= ~ADC0CN0_ADGN__FMASK;
  ADC0CN0 |= ADC0CN0_ADEN__ENABLED | ADC0CN0_ADGN__GAIN_0P5;
  // [ADC0CN0 - ADC0 Control 0]$

}

extern void
PWM_0_enter_DefaultMode_from_RESET (void)
{
  // $[Stop PWM]
  SFRPAGE = 0x10;
  PWMCFG1 &= ~(PWMCFG1_PWMEN__BMASK);
  // [Stop PWM]$

  // $[PWMCKDIV - PWMCKDIV]
  // [PWMCKDIV - PWMCKDIV]$

  // $[PWMCFG0 - PWM Configuration 0]
  /***********************************************************************
   - Enable clock to the PWM module
   - PWM will operate in Edge-aligned mode
   - Channel 0, Channel 1, and Channel 2 will be synchronously updated
   - PWM will continue running on breakpoints in debug mode
   - Rising edge on the enabled external trigger will start PWM counter
   - Disable Kill0 signal to halt the PWM
   ***********************************************************************/
  PWMCFG0 = PWMCFG0_PWMCLKEN__ENABLE | PWMCFG0_PWMMODE__EDGE
      | PWMCFG0_SYNCUPD__CH0CH1CH2 | PWMCFG0_DBGSTLEN__DISABLE
      | PWMCFG0_TRGESEL__REDGE | PWMCFG0_KILL0EN__DISABLE;
  // [PWMCFG0 - PWM Configuration 0]$

  // $[PWMCFG1 - PWM Configuration 1]
  // [PWMCFG1 - PWM Configuration 1]$

  // $[PWMCFG2 - PWM Configuration 2]
  /***********************************************************************
   - Do nothing
   - PWM triggered by software setting PWMEN
   - Enable PWM Channel 0
   - Enable PWM Channel 1
   - Enable PWM Channel 2
   ***********************************************************************/
  PWMCFG2 = PWMCFG2_TRGSEL__DISABLE | PWMCFG2_CH0EN__ENABLE
      | PWMCFG2_CH1EN__ENABLE | PWMCFG2_CH2EN__ENABLE | PWMCFG2_CNTRZERO__ZERO;
  // [PWMCFG2 - PWM Configuration 2]$

  // $[PWMCFG3 - PWMCFG3]
  // [PWMCFG3 - PWMCFG3]$

  // $[PWML - PWML]
  // [PWML - PWML]$

  // $[PWMH - PWMH]
  // [PWMH - PWMH]$

  // $[PWMLIML - PWMLIML]
  /***********************************************************************
   - PWM Counter Limit LSB = 0xFF
   ***********************************************************************/
  PWMLIML = (0xFF << PWMLIML_PWMLIML__SHIFT);
  // [PWMLIML - PWMLIML]$

  // $[PWMLIMH - PWMLIMH]
  /***********************************************************************
   - PWM Counter Limit MSB = 0xFF
   ***********************************************************************/
  PWMLIMH = (0xFF << PWMLIMH_PWMLIMH__SHIFT);
  // [PWMLIMH - PWMLIMH]$

  // $[PWMDTIPLIM - PWMDTIPLIM]
  // [PWMDTIPLIM - PWMDTIPLIM]$

  // $[PWMDTINLIM - PWMDTINLIM]
  // [PWMDTINLIM - PWMDTINLIM]$

  // $[PWMIE - PWMIE]
  // [PWMIE - PWMIE]$

  // $[PWM On]
  PWMCFG1 |= PWMCFG1_PWMEN__ENABLE;
  // [PWM On]$

}

extern void
PWMCH_0_enter_DefaultMode_from_RESET (void)
{
  // $[PWMCPL0 - Ch0 Compare Value LSB]
  // [PWMCPL0 - Ch0 Compare Value LSB]$

  // $[PWMCPH0 - Ch0 Compare Value MSB]
  // [PWMCPH0 - Ch0 Compare Value MSB]$

  // $[PWMCPUDL0 - Ch0 Compare Value Update LSB]
  // [PWMCPUDL0 - Ch0 Compare Value Update LSB]$

  // $[PWMCPUDH0 - Ch0 Compare Value Update MSB]
  // [PWMCPUDH0 - Ch0 Compare Value Update MSB]$

}

extern void
PWMCH_1_enter_DefaultMode_from_RESET (void)
{
  // $[PWMCPL1 - Ch1 Compare Value LSB]
  // [PWMCPL1 - Ch1 Compare Value LSB]$

  // $[PWMCPH1 - Ch1 Compare Value MSB]
  // [PWMCPH1 - Ch1 Compare Value MSB]$

  // $[PWMCPUDL1 - Ch1 Compare Value Update LSB]
  // [PWMCPUDL1 - Ch1 Compare Value Update LSB]$

  // $[PWMCPUDH1 - Ch1 Compare Value Update MSB]
  // [PWMCPUDH1 - Ch1 Compare Value Update MSB]$

}

extern void
PWMCH_2_enter_DefaultMode_from_RESET (void)
{
  // $[PWMCPL2 - Ch2 Compare Value LSB]
  // [PWMCPL2 - Ch2 Compare Value LSB]$

  // $[PWMCPH2 - Ch2 Compare Value MSB]
  // [PWMCPH2 - Ch2 Compare Value MSB]$

  // $[PWMCPUDL2 - Ch2 Compare Value Update LSB]
  // [PWMCPUDL2 - Ch2 Compare Value Update LSB]$

  // $[PWMCPUDH2 - Ch2 Compare Value Update MSB]
  // [PWMCPUDH2 - Ch2 Compare Value Update MSB]$

}

extern void
TIMER16_2_enter_DefaultMode_from_RESET (void)
{
  // $[Timer Initialization]
  // Save Timer Configuration
  uint8_t TMR2CN0_TR2_save;
  TMR2CN0_TR2_save = TMR2CN0 & TMR2CN0_TR2__BMASK;
  // Stop Timer
  TMR2CN0 &= ~(TMR2CN0_TR2__BMASK);
  // [Timer Initialization]$

  // $[TMR2CN1 - Timer 2 Control 1]
  // [TMR2CN1 - Timer 2 Control 1]$

  // $[TMR2CN0 - Timer 2 Control]
  // [TMR2CN0 - Timer 2 Control]$

  // $[TMR2H - Timer 2 High Byte]
  // [TMR2H - Timer 2 High Byte]$

  // $[TMR2L - Timer 2 Low Byte]
  // [TMR2L - Timer 2 Low Byte]$

  // $[TMR2RLH - Timer 2 Reload High Byte]
  /***********************************************************************
   - Timer 2 Reload High Byte = 0x60
   ***********************************************************************/
  TMR2RLH = (0x60 << TMR2RLH_TMR2RLH__SHIFT);
  // [TMR2RLH - Timer 2 Reload High Byte]$

  // $[TMR2RLL - Timer 2 Reload Low Byte]
  /***********************************************************************
   - Timer 2 Reload Low Byte = 0x7F
   ***********************************************************************/
  TMR2RLL = (0x7F << TMR2RLL_TMR2RLL__SHIFT);
  // [TMR2RLL - Timer 2 Reload Low Byte]$

  // $[TMR2CN0]
  /***********************************************************************
   - Start Timer 2 running
   ***********************************************************************/
  TMR2CN0 |= TMR2CN0_TR2__RUN;
  // [TMR2CN0]$

  // $[Timer Restoration]
  // Restore Timer Configuration
  TMR2CN0 |= TMR2CN0_TR2_save;
  // [Timer Restoration]$

}

